name: website
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8